/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jFrame;
import java.lang.System.Logger;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author pc
 */
public class FacultyLogin extends javax.swing.JFrame {

    /**
     * Creates new form FacultyLogin
     */
    public FacultyLogin() {
        initComponents();
        Connect();
    
      }
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    public void Connect(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/sahyadri_library_management_system","root","Sahyadri@157");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(FacultyLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        emailid = new javax.swing.JTextField();
        faculty_number = new javax.swing.JTextField();
        btnFLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("WElcome Sahyadri LMS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 42, 158, -1));

        jLabel2.setText("Faculty Login");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 100, 91, -1));

        jLabel3.setText("Email ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 160, 59, -1));

        jLabel4.setText("Faculty Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 259, -1, -1));
        getContentPane().add(emailid, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 157, 71, -1));
        getContentPane().add(faculty_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 267, 71, -1));

        btnFLogin.setText("Login as Register");
        btnFLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnFLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFLoginActionPerformed
        // TODO add your handling code here:
       String FacultyEmail = emailid.getText();
String FacultyNO = faculty_number.getText();

try {
    pst = con.prepareStatement("SELECT * FROM FACULTY WHERE emailid = ? AND faculty_number = ?");
    pst.setString(1, FacultyEmail);
    pst.setString(2, FacultyNO);

    rs = pst.executeQuery();

    if (rs.next()) {
        new FacultyHome().setVisible(true);
        this.setVisible(false);
    } else {
        JOptionPane.showMessageDialog(this, "Login Credentials Incorrect");
    }
} catch (SQLException ex) {
    // Log the details of the SQL exception for debugging
    Logger.getLogger(FacultyLogin.class.getName()).log(Level.SEVERE, "SQL Exception: " + ex.getMessage(), ex);
    JOptionPane.showMessageDialog(this, "Login failed! Please check the logs for details.");
}
      
    }//GEN-LAST:event_btnFLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacultyLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacultyLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacultyLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacultyLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacultyLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFLogin;
    private javax.swing.JTextField emailid;
    private javax.swing.JTextField faculty_number;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
