package jFrame;


import jFrame.AdminLogin;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author pc
 */
public class MainOpen extends javax.swing.JFrame {

    /**
     * Creates new form MainOpen
     */
    public MainOpen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnlibstaff = new javax.swing.JButton();
        btnstudent = new javax.swing.JButton();
        btnfaculty = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("WELCOME TO SAHYADRI LIBRARY MANAGEMENT SYSTEM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 78, -1, -1));

        btnlibstaff.setBackground(new java.awt.Color(255, 51, 51));
        btnlibstaff.setText("LIBRARY-STAFF");
        btnlibstaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlibstaffActionPerformed(evt);
            }
        });
        getContentPane().add(btnlibstaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 167, 179, 136));

        btnstudent.setBackground(new java.awt.Color(102, 255, 102));
        btnstudent.setText("STUDENTS");
        btnstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstudentActionPerformed(evt);
            }
        });
        getContentPane().add(btnstudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 167, 143, 136));

        btnfaculty.setText("FACULTY");
        btnfaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfacultyActionPerformed(evt);
            }
        });
        getContentPane().add(btnfaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 346, 177, 111));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlibstaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlibstaffActionPerformed
        // TODO add your handling code here:
        new AdminLogin().setVisible(true);
    }//GEN-LAST:event_btnlibstaffActionPerformed

    private void btnfacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfacultyActionPerformed
        // TODO add your handling code here:
        new FacultyLogin().setVisible(true);
    }//GEN-LAST:event_btnfacultyActionPerformed

    private void btnstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstudentActionPerformed
        // TODO add your handling code here:
        new StudentLogin().setVisible(true);
    }//GEN-LAST:event_btnstudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainOpen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainOpen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainOpen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainOpen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainOpen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfaculty;
    private javax.swing.JButton btnlibstaff;
    private javax.swing.JButton btnstudent;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
