/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jFrame;
import java.sql.*;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


public final class ManageBooks extends javax.swing.JFrame {
        Connection con=null;
        Statement st=null;
        PreparedStatement pst=null;
        ResultSet rs=null;
        
    /**
     * Creates new form ManageBooks
     * @throws java.sql.SQLException
     */
    public ManageBooks() throws SQLException{
            try {
                initComponents();
               
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sahyadri_library_management_system", "root", "Sahyadri@157");
                showRecord();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ManageBooks.class.getName()).log(Level.SEVERE, null, ex);
            }

    }
    
    public void showRecord(){
       
            try {
        pst = con.prepareStatement("SELECT * FROM BOOKS");
        rs = pst.executeQuery();
        ResultSetMetaData rsm = rs.getMetaData();
        int n = rsm.getColumnCount();
        DefaultTableModel df = (DefaultTableModel) bookrecords.getModel();
        df.setRowCount(0);

        while (rs.next()) {
            Vector obj = new Vector();
            for (int i = 1; i <= n; i++) {
                obj.add(rs.getString(i));
            }
            df.addRow(obj);
        }
    } catch (SQLException ex) {
        Logger.getLogger(ManageBooks.class.getName()).log(Level.SEVERE, null, ex);
    }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Btnupdate = new javax.swing.JButton();
        Btndelete = new javax.swing.JButton();
        searchrecord = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bookname = new javax.swing.JTextField();
        authorname = new javax.swing.JTextField();
        domain = new javax.swing.JTextField();
        qty = new javax.swing.JTextField();
        rack = new javax.swing.JTextField();
        edition = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookrecords = new javax.swing.JTable();
        btnaddbooks = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1028, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1028, -1));

        Btnupdate.setText("UPDATE");
        Btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(Btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 540, -1, 30));

        Btndelete.setText("Delete");
        Btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 530, -1, -1));
        getContentPane().add(searchrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 135, 530, 38));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 135, 123, 39));

        jLabel1.setText("Edition");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 513, 56, -1));

        jLabel2.setText("BooK Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 279, -1, -1));

        jLabel3.setText("Author Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 328, -1, -1));

        jLabel4.setText("Domain");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 374, -1, -1));

        jLabel5.setText("Quantity");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 428, -1, -1));

        jLabel6.setText("Rack No.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 473, -1, -1));
        getContentPane().add(bookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 276, 251, -1));
        getContentPane().add(authorname, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 325, 251, -1));

        domain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domainActionPerformed(evt);
            }
        });
        getContentPane().add(domain, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 371, 251, -1));
        getContentPane().add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 425, 251, -1));
        getContentPane().add(rack, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 470, 251, -1));
        getContentPane().add(edition, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 510, 251, -1));

        bookrecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Id", "Book Name", "Author Name", "Domain", "Quantity", "Rack", "Edition"
            }
        ));
        jScrollPane1.setViewportView(bookrecords);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 930, 140));

        btnaddbooks.setText("Add Books");
        btnaddbooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddbooksActionPerformed(evt);
            }
        });
        getContentPane().add(btnaddbooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        DefaultTableModel ob=(DefaultTableModel) bookrecords.getModel();
            TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(ob);
            bookrecords.setRowSorter(obj);
            obj.setRowFilter(RowFilter.regexFilter(searchrecord.getText()));
    }//GEN-LAST:event_btnSearchActionPerformed

    private void domainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_domainActionPerformed

    private void btnaddbooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddbooksActionPerformed
        // TODO add your handling code here:
             try {
    
    String bookName = bookname.getText();
    String authorName = authorname.getText();
    String Domain = domain.getText();
    String quantity = qty.getText();
    String rackNo = rack.getText();
    String Edition = edition.getText();

    // Simple validation: Check if any of the fields are empty
    if (authorName.isEmpty() || Domain.isEmpty() || bookName.isEmpty() || quantity.isEmpty() || rackNo.isEmpty() || Edition.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields before adding a book.");
        return;  // Stop the process if any field is empty
    }

    pst = con.prepareStatement("INSERT INTO BOOKS(book_name, author_name, domain, quantity, rack_no, edition) VALUES(?,?,?,?,?,?)");
    pst.setString(1, bookName);
    pst.setString(2, authorName);
    pst.setString(3, Domain);
    pst.setString(4, quantity);
    pst.setString(5, rackNo);
    pst.setString(6, Edition);

    int k = pst.executeUpdate();
    System.out.println("Rows affected: " + k);

    if (k == 1) {
        JOptionPane.showMessageDialog(this, "Book added successfully");
        bookname.setText("");
        authorname.setText("");
        domain.setText("");
        qty.setText("");
        rack.setText("");
        edition.setText("");
    } else {
        JOptionPane.showMessageDialog(this, "Failed to add book");
    }
} catch (SQLException ex) {
    JOptionPane.showMessageDialog(this, "Failed to add book! Error: " + ex.getMessage());
    Logger.getLogger(ManageBooks.class.getName()).log(Level.SEVERE, null, ex);
}
             showRecord();
    }//GEN-LAST:event_btnaddbooksActionPerformed

    private void BtnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnupdateActionPerformed
        try {
    pst = con.prepareStatement("UPDATE BOOKS SET author_name=?, domain=?, quantity=?, rack_no=?, edition=? WHERE book_name=?");
    pst.setString(1, authorname.getText());
    pst.setString(2, domain.getText());
    pst.setString(3, qty.getText());
    pst.setString(4, rack.getText());
    pst.setString(5, edition.getText());
    pst.setString(6, bookname.getText());
    
    pst.executeUpdate();
    showRecord();
} catch (SQLException ex) {
    Logger.getLogger(ManageBooks.class.getName()).log(Level.SEVERE, null, ex);
}

        
    }//GEN-LAST:event_BtnupdateActionPerformed

    private void BtndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtndeleteActionPerformed
        // TODO add your handling code here:
      try {
    pst = con.prepareStatement("DELETE FROM books WHERE book_name=?");
    pst.setString(1, bookname.getText());  // Assuming bookname is a JTextField or similar
    pst.executeUpdate();
    showRecord();
    // TODO add your handling code here:
} catch (SQLException ex) {
    Logger.getLogger(ManageBooks.class.getName()).log(Level.SEVERE, null, ex);
}

    }//GEN-LAST:event_BtndeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new ManageBooks().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(ManageBooks.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btndelete;
    private javax.swing.JButton Btnupdate;
    private javax.swing.JTextField authorname;
    private javax.swing.JTextField bookname;
    private javax.swing.JTable bookrecords;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnaddbooks;
    private javax.swing.JTextField domain;
    private javax.swing.JTextField edition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField qty;
    private javax.swing.JTextField rack;
    private javax.swing.JTextField searchrecord;
    // End of variables declaration//GEN-END:variables
}
